### ISSUE TITLE
Hi Finally got it back working again I get this weird error in the log?

### ISSUE THREAD

**Issue by MackPit** [fuatakgun/eufy_security_addon#1]
2021-12-04 10:57:11.468  ERROR Status return code not 200 
{
  status: 423,
  statusText: 'Locked'

**Comment by MackPit** [comment]
Set it back to AUS for country code and it did this.
Unable to start driver InvalidCountryCodeError: Invalid ISO 3166-1 Alpha-2 country code
    at HTTPApi.setCountry (/usr/src/app/node_modules/eufy-security-client/build/http/api.js:68:19)
    at new EufySecurity (/usr/src/app/node_modules/eufy-security-client/build/eufysecurity.js:104:18)
    at /usr/src/app/dist/bin/server.js:51:20
    at Object.<anonymous> (/usr/src/app/dist/bin/server.js:77:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

**Comment by fuatakgun** [comment]
following the error code, it is angry about country code: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
try with AU

**Comment by MackPit** [comment]
Done that now they are using token for login?  Does that mean you need to re code it?  Token I never changed any settings at all, except trying to re install your packages.

**Comment by fuatakgun** [comment]
inside home assistant, I do not think I have enabled storage for this add-on, every time, it tries to login with credentials without using token.
